# Generated by Django 3.2 on 2021-04-22 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passedlessons',
            options={'verbose_name': 'Законченный урок', 'verbose_name_plural': 'Законченные уроки'},
        ),
        migrations.AlterModelOptions(
            name='schedulelesson',
            options={'verbose_name': 'Планируемый урок', 'verbose_name_plural': 'Планируемые уроки'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AddField(
            model_name='schedulelesson',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notebook.teacher'),
            preserve_default=False,
        ),
    ]
