# Generated by Django 3.2 on 2021-05-25 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0002_auto_20210422_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notebook.schedule'),
        ),
    ]
